name: GitHub CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lint and Test
        run: |
          cp token.sample.js token.js
          npm install
          npm run lint
          npm test
